services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    environment:
      - TZ=Asia/Bangkok
      - GLANCES_OPT=-w # Glances option to run as a web server
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    ports:
      - "61208:61208"