services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      # username
      POSTGRES_USER: 
      # password
      POSTGRES_PASSWORD:
      # db name
      POSTGRES_DB:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: