VARS = vars.env

signup:
	hurl -i --variables-file $(VARS) signup.hurl

get-token:
	hurl -i --variables-file $(VARS) get-token.hurl

sync-customer:
	hurl -i --variables-file $(VARS) sync-customer.hurl

me:
	hurl -i --variables-file $(VARS) me.hurl

line-webhook:
	hurl -i --variables-file $(VARS) line-webhook.hurl

